library(tidyverse)
library(shiny)
library(shinythemes)
library(sbo)
ngram_model <- load("../models/ngram_model.Rda")

# Define UI for app that draws a histogram ----
ui <- navbarPage(
  # App title ----
  strong("Next Word Prediction Application"),
  
  theme = shinytheme("flatly"),
  
  # Sidebar layout with input and output definitions ----
  tabPanel("Prediction Tool",
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      textInput("text", h3("Text Input"), 
                value = "Enter text..."),
      actionButton(inputId = "Run", "Run")
      ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      tabsetPanel(type = "tabs",
                  tabPanel("Next Word Predictions",
                           htmlOutput("words")),
                  tabPanel("Babble",
                           htmlOutput("babble"))),
      width = 8
    )),
  tabPanel("Documentation",
           mainPanel(
             h4("Purpose"),
             "This application can uses a", 
             a("Stupid Back-off (SBO) N-gram model", 
               href = "https://www.aclweb.org/anthology/D07-1090.pdf"),
             "to predict upcoming text given a word or short phrase. While any text can be given to the model, the model will only utilize the last 3 words of the phrase for prediction. Predictions come in 2 formats: next word predictions and “babbles”. The next word predictions will give the 3 most likely words for a given input text. “Babbles” randomly construct an entire sentence based on the input text. The final model for this project was built using the",
             code("sbo"),
             "R package.",
             h4("How to Use"),
             "Predictions can be generated by:",
             tags$ol(
               tags$li("Providing text to the", code("Text Input"), "box"),
               tags$li("Clicking", code("Run"))
             ),
             "The user can switch back and forth between the “Next Word Predictions” and “Babble” tabs to see the two forms of predictions. Clicking “Run” multiple times will refresh the “Babble” sentence, but the “Next Word Predictions” will remain unchanged. Some things to note about the results:",
             tags$ul(
               tags$li("Subsequent “Babble” results, being random, can be the same between model calls and may require multiple clicks for unique results."),
               tags$li("The selected model can predict the end of a sentence. The result “.!?” Indicates the model is predicting the end of a sentence.")
             ),
             h4("Sources"),
             "This model was built using news, blogs, and Twitter data from SwiftKey as part of the Johns Hopkins Data Science Specialization Capstone project on Coursera. The data can be downloaded",
             a("here.", 
               href = "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"),
             "Examples provided by other bloggers analysis helped guide this project. In particular, the",
             a("SBO vignette by Valerio Gherardi,",
               href = "https://cran.r-project.org/web/packages/sbo/vignettes/sbo.html)"),
             "the",
             a("TensorFlow example from Julia Silge,",
               href = "https://www.r-bloggers.com/2018/10/tensorflow-jane-austen-and-text-generation/"),
             "and the",
             a("Markov chain example from Alex Bresler",
               href = "https://github.com/abresler/markovifyR"),
             "were all influential on this final model desing.",
             width = 5 
           )
  )
  )

